language: node_js
node_js:
- '8'

env:
  global:
    secure: jT4LzOlJ63nIM/mtTXX9Vc75utPqVgKvQkUieFgpFD31STETbyAEUSpXaFU9BCDqAAHyCqT4ioMx+MAmc9Na1EvvnSmA0FUnggzAyJ4R/reHK9bKmt2ObyDn3ekCR9uYjuGA2UZuzlelWQd++5lvZHGFqfYCjeGBqhDE06A1fXwvPeAptAtCtVQ1t0ZN3dSdaF5lQMFxyw5QXjFxjuL3knrjb2GwWEa0p71/aAthHlM7TDdne406qoOG+honWFyTPQM3/DQjNhBPnMZup/aSs6xc/zmtqHnR68hopECfHlKwwSRefZA2VmBD7mPZT3oOaM8x1/+e0SxVXxCuV3k0i+mT7mkHyhvawWLrQie2SPGfmdkc63AEcAkv52yQ0KSLEn5tnnjqalp8v2BewblDGPeowmJVR3Q1atwdzXrlpf7jgzwP3L42MAEuTPUdGGLax+QBoEg0tvff0j64uqYIMFRNL3Bk76NAkd01+QTEDd2uUV/uLg8OlWdlEwLUfUeLgo8yQSBQkzuTzb6Hro2HBICf5liBGmw5AjKsQ1t+haAYPPsBjinsSLQHcCN1cAJrbaYaiXz0sFdfglVtDPSGmISuqsPEnz9lXmBXxVL0L85w1ULAiKbiyYp9xtivAsvdE1Yv3BkA1KmW8kbIDgi0Zm2/D136y8TuMGxHo72sEgQ=

install:
- yarn install

script:
- yarn build

deploy:
  provider: surge
  project: ./public/
  domain: react_prerender_site.surge.sh
  skip_cleanup: true
  on: master