language: node_js
node_js:
- '8'

env:
  global:
    secure: TmUT5bjHq8G+I9o3feyU+2XIKCy51Pg9R4BEfA3N5AonWPxNpGzUeDAk+UPzBtgFLrrVgVF3I4bwcIies2HzZCiAZ5YDlDr2AjbOGW5H/7KkJMoXk48y3wWUAHfQE81bO6hEt3qXkR3al/zb22gNeg6aS08fUekzSt0Mbv8bEzO6FVf8TX+xV8pSjS0dnCFvw8nuxglQPib+eUBnKjBExKvLzBKTTYuFz9gcf257SUPu31RoXSI8Kv6Lxm8kjkyvToEHEB+CPAsmrj1X08seykqpMlY1dfUUpfdpEdsb4DsAEBcCry/BUBr7w7QPs4di2j3sl9uncS7b/QwPSMzCybudDH8Rcuq3rVQzAa2OoSEKG4leVCqYwAkF2pWskLEHI4e1qVJkBqIlnogjhNRFvv3WHwmZFcy7oA6v8df3Qi8UTQujhhVGGhbHtxzUBvD6aw1z4dof3ekUN2OVBvAyPwyZiC04XMr4POPD2IAxn9R6sj7esNeewkIOIHN5cJ4z1/yLdPB5b5W1U52mRk7+9cPYRlVnga+11gY5+HcH9PD/Rxgi9x3fcQEXGcqlUdJFgA+qGijB5iyXdYyaBOoR8AYS/oZCxrEJi17+OOzoVcmKcpCnQNupee7PbBQfezXJudNDg4jgV9Uxxzn8RlliRh+bbYHzK58578ENgUUUG3Y=

install:
- yarn install

script:
- yarn build

# deploy:
#   provider: pages
#   local-dir: public
#   skip-cleanup: true
#   github-token: "$GH_TOKEN"
#   keep-history: true
#   verbose: true
#   on:
#     branch: master